version: '3.3'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: kwetter
      MYSQL_USER: kwetter
      MYSQL_PASSWORD: kwetter
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - kwetternet

  kwetter_api:
    image: hugovdv/kwetter_api:circleci-exp
    environment:
      WAIT_HOSTS: 1
    ports:
      - 8080:8080
    networks:
      - kwetternet

  kwetter_webapp:
    image: hugovdv/kwetter_webapp:circleci-exp
    ports:
      - 4200:4200

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

networks:
  kwetternet:
    driver: bridge