# Java Maven CircleCI 2.1 configuration file

version: 2.1

jobs:
  dependencies_backend:
    executor: java
    steps:
      - attach_workspace_all
#      - restore_cache_backend
      - run:
          name: Maven Go-Offline
          command: ls -al
#          cd $SOURCE_PATH && mvn dependency:go-offline
      - save_cache_backend

  build_backend:
    executor: java
    steps:
      - attach_workspace_all
      - restore_cache_backend
      - run:
          name: Maven Go-Offline
          command: cd $SOURCE_PATH && mvn dependency:go-offline
      - save_cache_backend

      - attach_workspace_all
      - restore_cache_backend
      - run:
          name: Build Backend
          command: cd $SOURCE_PATH && mvn install -DskipTests
      - persist_workspace_backend

  test_backend:
    executor: java
    steps:
      - attach_workspace_all
      - restore_cache_backend
      - run:
          name: Test Backend
          command: cd $SOURCE_PATH && mvn test
      - persist_workspace_backend_tests

  sonarqube:
    executor: java
    steps:
      - run:
          command: |
            cd $SOURCE_PATH
            mvn sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=$SONAR_ORG \
            -Dsonar.projectKey=$SONAR_P_KEY \
            -Dsonar.login=$SONAR_LOGIN

workflows:
  build_and_test:
    jobs:
      - dependencies_backend
      - build_backend:
          requires:
            - dependencies_backend
      - test_backend:
          requires:
            - build_backend
      - sonarqube:
          requires:
            - test_backend

executors:
#  python:
#    docker:
#      - image: python

  java:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      MAVEN_OPTS: -Xmx3200m
      SOURCE_PATH: api

#  node:
#    docker:
#      - image: circleci/node:10.15.3
#    environment:
#      SOURCE_PATH: webapp

commands:
  attach_workspace_all:
    steps:
      - attach_workspace:
          at: .

  persist_workspace_backend:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - api

  persist_workspace_backend_tests:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - api/target

  persist_workspace_sonar:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - sonar-scanner-3.3.0.1492-linux

  restore_cache_backend:
    steps:
      - restore_cache:
          keys:
            - maven-v3-{{ checksum "api/pom.xml" }}
            - maven-v3-

  save_cache_backend:
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: maven-v3-{{ checksum "api/pom.xml" }}
