# Java Maven CircleCI 2.1 configuration file

version: 2.1

workflows:
  build_and_test:
    jobs:
      - checkout
      - dependencies_backend:
          requires:
            - checkout
      - dependencies_frontend:
          requires:
            - checkout
      - build_backend:
          requires:
            - dependencies_backend
      - build_frontend:
          requires:
            - dependencies_frontend
      - test_backend:
          requires:
            - build_backend
      - lint_frontend:
          requires:
            - build_frontend
      - sonarqube:
          requires:
            - test_backend
            - lint_frontend

jobs:
  checkout:
    executor: python
    steps:
      - checkout
      - persist_workspace_backend
      - persist_workspace_frontend

  dependencies_backend:
    executor: java
    steps:
      - attach_workspace
      - restore_cache_backend
      - run:
          name: Maven offline
          command: cd $SOURCE_PATH && mvn dependency:go-offline
      - save_cache_backend

  dependencies_frontend:
    executor: node
    steps:
      - attach_workspace
      - restore_cache_frontend
      - run:
          name: Install dependencies
          command: ls -al
#          cd $SOURCE_PATH && npm install
      - save_cache_frontend

  build_backend:
    executor: java
    steps:
      - attach_workspace
      - restore_cache_backend
      - run:
          name: Maven offline
          command: cd $SOURCE_PATH && mvn dependency:go-offline
      - save_cache_backend

      - attach_workspace
      - restore_cache_backend
      - run:
          name: Building api
          command: cd $SOURCE_PATH && mvn install -DskipTests
      - persist_workspace_backend

  build_frontend:
    executor: node
    steps:
      - attach_workspace
      - restore_cache_frontend
      - run:
          name: Build webapp
          command: cd $SOURCE_PATH && npm run build
      - persist_workspace_frontend_dist

  test_backend:
    executor: java
    steps:
      - attach_workspace
      - restore_cache_backend
      - run:
          name: Testing api
          command: cd $SOURCE_PATH && mvn test
      - persist_workspace_backend_tests

  lint_frontend:
    executor: node
    steps:
      - attach_workspace
      - restore_cache_frontend
      - run:
          name: Linting webapp
          command: cd $SOURCE_PATH && npm run lint
      - store_test_results:
          path: test-results/lint_frontend

  sonarqube:
    executor: java
    steps:
      - attach_workspace
      - restore_cache_backend
      - run:
          command: |
            cd $SOURCE_PATH
            mvn sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=$SONAR_ORG \
            -Dsonar.projectKey=$SONAR_P_KEY \
            -Dsonar.login=$SONAR_LOGIN

executors:
  python:
    docker:
      - image: python

  java:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      MAVEN_OPTS: -Xmx3200m
      SOURCE_PATH: api

  node:
    docker:
      - image: circleci/node:10.15.3
    environment:
      SOURCE_PATH: webapp

commands:
  attach_workspace:
    steps:
      - attach_workspace:
          at: .

  persist_workspace_backend:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - api

  persist_workspace_backend_tests:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - api/target

  persist_workspace_frontend:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - webapp

  persist_workspace_frontend_dist:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - webapp/dist

  persist_workspace_sonar:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - sonar-scanner-3.3.0.1492-linux

  restore_cache_backend:
    steps:
      - restore_cache:
          keys:
            - maven-v3-{{ checksum "api/pom.xml" }}
            - maven-v3-

  restore_cache_frontend:
    steps:
      - restore_cache:
          keys:
            - node-v5-{{ checksum "webapp/package.json" }}
            - node-v5-

  save_cache_backend:
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: maven-v3-{{ checksum "api/pom.xml" }}

  save_cache_frontend:
    steps:
      - save_cache:
          paths:
            - webapp/node_modules
          key: node-v5-{{ checksum "webapp/package.json" }}
