# Java Maven CircleCI 2.1 configuration file

version: 2.1

jobs:
  build_test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "api/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd api && mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "api/pom.xml" }}

      # run api tests
      - run:
          command: cd api && mvn test

  sonarqube:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - run:
          command: |
            ls
#            cd api &&
#            mvn sonar:sonar \
#            -Dsonar.host.url=https://sonarcloud.io \
#            -Dsonar.organization=$SONAR_ORG \
#            -Dsonar.projectKey=$SONAR_P_KEY \
#            -Dsonar.login=$SONAR_LOGIN

workflows:
  build_and_test:
    jobs:
#      - build_test
      - sonarqube
